### ISSUE TITLE
What's the catch behing 'login' requirment to add subtitles to the local video files for local consumption?

### ISSUE THREAD

**Issue by zenny** [bmcmahen/Subtitles#11]
@bmcmahen Hi Ben,

Can the developer elaborate on why one has to login to add subtitles to local files for local installation of Subtitles? Sounds odd?

Cheers and happy holidays,
/z

**Comment by bmcmahen** [comment]
It's just easier based on the current setup, which assumes that a user will want to create various captioning projects, and revisit them potentially in the future. I don't think there's really anything preventing the implementation of anonymous caption creations, other than my limited time and energy. 

Thanks for the well wishes, and happy holidays to you too!
