### ISSUE TITLE
Hi, did anyone manage to run this project using the meteor 1.1.0.2?

### ISSUE THREAD

**Issue by lyair1** [bmcmahen/Subtitles#13]
Hi, I tried to run the project, when I first typed "meteor" I got:

This project says that it uses Meteor 0.6.6.1, but you don't have that version of Meteor installed and the Meteor update servers don't have it either. Please edit the .meteor/release file in the project and change it to a
valid Meteor release.

I changed it to 1.1.0.2, mange to fix some syntax errors in the html files but then I got an error in the Oath.js file, I deleter all the file content and now when I run meteor it doesn't crush but when I go to my browser an type "localhost:3000" my browser stuck and I get "not responding" message.

please help

**Comment by Tzikas** [comment]
+1

**Comment by bmcmahen** [comment]
Yeah... this was built with a much, much older version of Meteor. I'll see if I can update it to a newer version whenever I have some spare time. I'd happily accept a PR that does this, too.

**Comment by lyair1** [comment]
No, I stated working on my own subtitles project, feel free to use it.

*https://github.com/lyair1/TAU-Subtitles
<https://github.com/lyair1/TAU-Subtitles>*



Thanks,
Yair

+972-545919286

**Comment by mediter** [comment]
can run locally, but when trying to create a new project, it requires login. all 3 social login options doesn't work when running locally.

**Comment by bmcmahen** [comment]
i recommend people use the new version built with react and firebase [found here](https://github.com/bmcmahen/captioner). this is really, really old code and i didn't know meteor was still a thing tbh.
